/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces/route'
import { Route as EditorRouteImport } from './routes/editor/route'
import { Route as IndexImport } from './routes/index'
import { Route as WorkspacesIndexImport } from './routes/workspaces/index'
import { Route as EditorIndexImport } from './routes/editor/index'

// Create/Update Routes

const WorkspacesRouteRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRoute,
} as any)

const EditorRouteRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorkspacesIndexRoute = WorkspacesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesRouteRoute,
} as any)

const EditorIndexRoute = EditorIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRoute
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRoute
    }
    '/editor/': {
      id: '/editor/'
      path: '/'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexImport
      parentRoute: typeof EditorRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexImport
      parentRoute: typeof WorkspacesRouteImport
    }
  }
}

// Create and export the route tree

interface EditorRouteRouteChildren {
  EditorIndexRoute: typeof EditorIndexRoute
}

const EditorRouteRouteChildren: EditorRouteRouteChildren = {
  EditorIndexRoute: EditorIndexRoute,
}

const EditorRouteRouteWithChildren = EditorRouteRoute._addFileChildren(
  EditorRouteRouteChildren,
)

interface WorkspacesRouteRouteChildren {
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

const WorkspacesRouteRouteChildren: WorkspacesRouteRouteChildren = {
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}

const WorkspacesRouteRouteWithChildren = WorkspacesRouteRoute._addFileChildren(
  WorkspacesRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRouteRouteWithChildren
  '/workspaces': typeof WorkspacesRouteRouteWithChildren
  '/editor/': typeof EditorIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorIndexRoute
  '/workspaces': typeof WorkspacesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/editor': typeof EditorRouteRouteWithChildren
  '/workspaces': typeof WorkspacesRouteRouteWithChildren
  '/editor/': typeof EditorIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor' | '/workspaces' | '/editor/' | '/workspaces/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/workspaces'
  id: '__root__' | '/' | '/editor' | '/workspaces' | '/editor/' | '/workspaces/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRouteRoute: typeof EditorRouteRouteWithChildren
  WorkspacesRouteRoute: typeof WorkspacesRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRouteRoute: EditorRouteRouteWithChildren,
  WorkspacesRouteRoute: WorkspacesRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/editor",
        "/workspaces"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/editor": {
      "filePath": "editor/route.tsx",
      "children": [
        "/editor/"
      ]
    },
    "/workspaces": {
      "filePath": "workspaces/route.tsx",
      "children": [
        "/workspaces/"
      ]
    },
    "/editor/": {
      "filePath": "editor/index.tsx",
      "parent": "/editor"
    },
    "/workspaces/": {
      "filePath": "workspaces/index.tsx",
      "parent": "/workspaces"
    }
  }
}
ROUTE_MANIFEST_END */
